name: gateway

services:
  traefik:
    image: traefik:v3.6.4
    container_name: gateway_traefik
    restart: unless-stopped

    command:
      - --api=true
      - --api.dashboard=true
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=false
      - --entrypoints.web.address=:80

    ports:
      - "80:80"
      # removed 8080:8080 (dashboard will be routed + protected)

    volumes:
      #   - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./dynamic:/etc/traefik/dynamic:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/tim/stacks/gateway/dynamic:/etc/traefik/dynamic:ro
  
    networks:
      - proxy

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      - traefik.http.routers.traefik.rule=Host(`traefik.lan.timscloud.net`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.middlewares=dash-allowlist@file,dash-auth@file

networks:
  proxy:
    external: true

