name: immich

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped

    volumes:
      # All Immich internal state (uploads, thumbs, encoded-video, etc.) in Docker volume
      - immich_data:/data
      - /etc/localtime:/etc/localtime:ro

      # External library on D:\ (read-only)
      - "/mnt/d/Epson v600:/ext_library:ro"

    networks:
      - internal
      - proxy
    
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      # Internal access (LAN)
      - traefik.http.routers.photos-lan.rule=Host(`photos.lan.timscloud.net`)
      - traefik.http.routers.photos-lan.entrypoints=web
      - traefik.http.routers.photos-lan.service=immich
      # optional but recommended:
      # - traefik.http.routers.photos-lan.middlewares=lan-only@docker

      # Public access (enable later)
      # - traefik.http.routers.photos-public.rule=Host(`photos.timscloud.net`)
      # - traefik.http.routers.photos-public.entrypoints=web
      # - traefik.http.routers.photos-public.service=immich

      - traefik.http.services.immich.loadbalancer.server.port=2283





  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - model-cache:/cache
    networks:
      - internal

  redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9
    restart: unless-stopped
    networks:
      - internal

  database:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - immich_pgdata:/var/lib/postgresql/data
    shm_size: 128mb
    networks:
      - internal

volumes:
  immich_data:
  immich_pgdata:
  model-cache:

networks:
  internal:
    driver: bridge
  proxy:
    external: true
